### ISSUE TITLE
power settings. power consumption mode

### ISSUE THREAD

**Issue by pennywise322** [elementary/switchboard-plug-power#237] opened 2023-06-29 20:56 UTC
### Problem

the problem is that in the settings it is not possible to set a different default energy consumption mode for connected to the mains and energy consumption from the accumulator.

### Proposal

I have a laptop and it would be nice if my laptop would work at full power when I am plugged in. but when I disconnect from the mains I want it to work in saving mode or balance. it would also be good to add power mode management to the system indicator battery icon on the panel. so that you don't have to go into the settings every time you want to change the electricity consumption mode, and you could do it easily and conveniently

**Comment by jeremypw** [comment] 2023-07-12 08:57
I am sure this can be fixed but there are a limited number of devs working on a lot of different things.  Please be patient.

**Comment by lenemter** [comment] 2024-01-27 07:43
Closing as duplicate of https://github.com/elementary/switchboard-plug-power/issues/227

**Closed by lenemter** 2024-01-27 07:43 UTC
Labels: Status: Confirmed
