### ISSUE TITLE
Changing suspend timeout changes dark theme to light 

### ISSUE THREAD

**Issue by fidelisakilan** [elementary/switchboard-plug-power#172] opened 2021-01-26 04:56 UTC
## What Happened

If i change timeout for suspend in power settings when i am in dark mode the system theme changes to light theme.But if i have light theme there is no problem

## Expected Behavior

expected to change the power timeouts without changing the theme

## Steps to Reproduce

1.Change system theme to dark style.
2.Go to Settings > Power  
3.Change the suspend when inactive time to something the system theme changes to light.

![image](https://user-images.githubusercontent.com/24905278/105802300-de210e80-5fc0-11eb-9e7a-d737e80ce9f6.png)

## Platform Information

![image](https://user-images.githubusercontent.com/24905278/105802327-ec6f2a80-5fc0-11eb-8bf1-e3e7840af2f2.png)

**Comment by danrabbit** [comment] 2021-05-19 01:24
Closing as a duplicate of #165

**Closed by danrabbit** 2021-05-19 01:24 UTC
