### ISSUE TITLE
Logind helper conflicts with Gtk3 install

### ISSUE THREAD

**Issue by danirabbit** [elementary/switchboard-plug-power#221] opened 2022-09-22 17:38 UTC
### What Happened?

The logind helper binary conflicts between the gtk4 and gtk3 packages

### Steps to Reproduce

Try to install both switchboard-plug-power and io.elementary.settings.power

### Expected Behavior

No conflicts, should be parallel installable

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by lenemter** [comment] 2024-02-10 04:02
Duplicate of https://github.com/elementary/switchboard-plug-power/issues/221

**Closed by lenemter** 2024-02-10 04:02 UTC
