### ISSUE TITLE
New Battery dedicated section

### ISSUE THREAD

**Issue by andirsun** [elementary/switchboard-plug-power#188] opened 2021-07-02 01:52 UTC
### Discussed in https://github.com/elementary/switchboard-plug-power/discussions/187

<div type='discussions-op-text'>

<sup>Originally posted by **andirsun** July  1, 2021</sup>
How about build a new section to see the battery stats in the power switchboard. 
We can get the history stats from the gnome-power-statistics and display in modern Gtk widgets 
This is the first step in this direction https://github.com/elementary/wingpanel-indicator-power/pull/190
From this : 
![Screenshot from 2021-07-01 20-47-12](https://user-images.githubusercontent.com/22928302/124208825-051ec780-daae-11eb-9729-65cfffda8263.png)
To something more modern like mac os does : 
![Screenshot from 2021-07-01 20-46-47](https://user-images.githubusercontent.com/22928302/124208863-17990100-daae-11eb-96b2-42e7d03fac17.png)
</div>

The first mockup that I took the base idea @lainsce 
![Vista(1)](https://user-images.githubusercontent.com/22928302/124286869-fe776b00-db14-11eb-854d-548715f46f84.png)

**Comment by cassidyjames** [comment] 2021-07-06 19:10
Duplicate of #156

**Closed by cassidyjames** 2021-07-06 19:10 UTC
