### ISSUE TITLE
In power settings, suspend is set to never for both battery and plugged in modes . However, the laptop still goes into a suspend state after approximately 30 minutes.

### ISSUE THREAD

**Issue by hackmaster0110** [elementary/switchboard-plug-power#116] opened 2019-06-05 15:23 UTC
In power settings, suspend is set to never for both battery and plugged in modes.However, the laptop still goes into a suspend state after approximately 30 minutes.I installed elementary os Juno 2 days back.I use dell inspiron 3542

**Comment by peteruithoven** [comment] 2019-06-07 12:56
This is a power plug specific issue so I've moved the issue.

**Comment by peteruithoven** [comment] 2019-06-07 12:57
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/switchboard-plug-power/issues/89

**Closed by peteruithoven** 2019-06-07 12:57 UTC
