### ISSUE TITLE
Computer always goes to sleep

### ISSUE THREAD

**Issue by kakogoxepa** [elementary/switchboard-plug-power#122] opened 2019-08-25 12:21 UTC
I set the settings everywhere so that the computer does not fall asleep. But he continues to fall asleep after about half an hour. I put the torrent to download and left. When i back the computer slept. Always like this. Correct it urgently, so it’s not possible to work normally. Since when the computer comes out of sleep, ripples and glitches appear on the screens, i have to reboot to make everything normal.
![info_my_pc](https://user-images.githubusercontent.com/39045905/63649880-e3cf5080-c74b-11e9-9010-4c98d5a5debd.png)

**Comment by kgrubb** [comment] 2019-08-25 16:42
This is possibly a duplicate of #89, can you try the steps in this comment: https://github.com/elementary/switchboard-plug-power/issues/89#issuecomment-461169400 and see if that resolves your issue?

**Comment by naggie** [comment] 2019-12-27 10:27
I also had this issue with my desktop computer. The workaround described works but it not scriptable due to the usage of `su` requiring subshells. I was able to use sudo instead after specifying the lightdm home directory with:

```
sudo -u lightdm env HOME=/var/lib/lightdm dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type nothing
```

**Comment by naggie** [comment] 2019-12-29 11:51
Further to this, if I lock my PC it says awake as expected; but after I log in the following morning it goes into standby

**Comment by naggie** [comment] 2020-01-05 09:30
I ended up disabling the ability to suspend altogether using systemd, as explained here: https://elementaryos.stackexchange.com/questions/16519/elementary-os-ignoring-suspend-disable

`sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target`

Not suitable for a laptop of course, but I'm running on a desktop do it's OK for me at least.

**Comment by kgrubb** [comment] 2020-04-15 20:04
This should be resolved now that the changes in https://github.com/elementary/switchboard-plug-power/pull/123 have been merged in and released!

**Closed by kgrubb** 2020-04-15 20:04 UTC

**Comment by naggie** [comment] 2020-04-15 22:32
Great to hear that, thanks @kgrubb -- I can use Elementary again!
