### ISSUE TITLE
Notebook suspendendo mesmo quando configurado para não suspender

### ISSUE THREAD

**Issue by andrelopesrigo** [elementary/switchboard-plug-power#137] opened 2020-02-16 12:50 UTC
O notebook está suspendendo mesmo estando configurado para nunca suspender quando ligado na tomada. Estou usando o Elementary 5.1.2.

**Comment by Kisuke-CZE** [comment] 2020-03-04 10:20
Yeah, some update broke this.

It's again the old situation, when user lightdm has different settings than user logged in.
Unfortunately, even if you fix it manually (which is not hard), on next reboot settings are restored.
Any idea what component is restoring those settings?

Temporary fix (until next reboot) is:
```
su - -s /bin/bash lightdm
dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type nothing
dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
```

After reboot settings are back to
```
sleep-inactive-ac-type = suspend
sleep-inactive-ac-timeout = 1200
```

**Comment by lenemter** [comment] 2024-02-10 08:37
Closing because I cannot reproduce the issue on my OS 7.1.

**Closed by lenemter** 2024-02-10 08:37 UTC
