### ISSUE TITLE
Changing power related setting resets system wide theme back to Default from Dark

### ISSUE THREAD

**Issue by rigglemania** [elementary/switchboard-plug-power#179] opened 2021-05-03 00:15 UTC
## What Happened
While tweaking a setting to the power behavior, it switched my system theme from dark back to the default light theme. This issue doesn't appear just limited to the power settings dialog as this also happened in the date time settings dialog when changing the format to AM/PM. I also found this isn't always 100% reproducible. In the one case it wasn't reproducible, I went back to the theme selection, flipped from Dark to Default and then back to Dark, and then went back to the Power settings where the bug was then reproducible again.

## Expected Behavior
Changing a system setting (other than the theme setting itself) should not change the default theme

## Steps to Reproduce
1. Ensure the theme is set to Dark
2. Open System Settings
3. Open Power
4. Change "Suspend when inactive for" to 1 hour
5. Watch theme change from Dark to Default

## Platform Information
elementary OS 6 Early Access
Linux 5.8.0-50-generic

I'm not sure if this matters, but I was running in Demo Mode as I'm wanting to wait a bit of time for some issues to be resolved before installing it on my disk.

**Comment by danrabbit** [comment] 2021-05-19 01:22
Closing as a duplicate of #165

**Closed by danrabbit** 2021-05-19 01:22 UTC
